repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: end-of-file-fixer
      - id: check-added-large-files
        args: ["--maxkb=1028"]
      - id: check-toml
      - id: trailing-whitespace
        exclude: ^(_vendor)
        args: [--markdown-linebreak-ext=md]
  - repo: https://github.com/crate-ci/typos
    rev: v1.19.0
    hooks:
      - id: typos
        args: ["--config", "./typos.toml", "./content/"]
        files: ^content|i18n
  - repo: "https://github.com/zricethezav/gitleaks"
    rev: v8.18.2
    hooks:
      - id: gitleaks
