baseURL = "https://prinzpiuz.in/"
languageCode = "en-us"
title = "prinzpiuz"
relativeURLs = true
enableEmoji = true
enableRobotsTXT = true
enableGitInfo = true
copyright = "© Copyright 2025, prinzpiuz"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "About"
    url = "/about/"
    weight = -110
  [[menu.main]]
    identifier = "blogs"
    name = "Blog"
    title = "Blog"
    url = "/post/"
    weight = -100
  [[menu.main]]
    identifier = "uses"
    name = "/Uses"
    title = "/Uses"
    url = "/uses/"
    weight = -90
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    title = "Projects"
    url = "/projects/"
    weight = -80
  [[menu.main]]
    identifier = "homelab"
    name = "Homelab"
    title = "Homelab"
    url = "/homelab/"
    weight = -70

[params]
  version="2.0.13"
  opengraph_io_api_key = "65b682c0-f713-473b-b75a-30e7eda27791"
  header_title = "PrinzPiuz"
  header_subtitle = "Software Engineer | Nuventure | Cochin"
  home_image = "/images/avatar.png"
  recent_posts = 5
  mainSections = ["posts", "post", "blog"]

  [params.author]
    name = "prinzpiuz"

  [[params.social]]
    fa_icon = "fab fa-github fa-1x"
    href = "https://github.com/prinzpiuz"
  [[params.social]]
    fa_icon = "fab fa-twitter fa-1x"
    href = "https://twitter.com/prinzpiuz/"
  [[params.social]]
    fa_icon = "fab fa-mastodon"
    href = "https://elk.zone/aana.site/@prinzpiuz"
  [[params.social]]
    fa_icon = "fas fa-images"
    href = "https://portfolio.pixelfed.social/prinzpiuz"
  [[params.social]]
    fa_icon = "fas fa-rss"
    href = "/index.xml"
    name = "RSS Feed"

[security]
  [security.http]
    urls = ['https://opengraph\.io/.*']
