baseURL = "https://prinzpiuz.in/"
languageCode = "en-us"
title = "prinzpiuz"
relativeURLs = true
enableEmoji = true
enableRobotsTXT = true
copyright = "&copy; Copyright 2024, prinzpiuz"
# Main menu items
[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "About"
    url = "/about/"
    weight = -110
  [[menu.main]]
    identifier = "blogs"
    name = "Blog"
    title = "Blog"
    url = "/post/"
    weight = -100
  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    title = "Categories"
    url = "/categories/"
    weight = -90
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    title = "Projects"
    url = "/projects/my-projects/index.html"
    weight = -80

# Configuration Features
[params]
  version="1.12.0"
  opengraph_io_api_key = "65b682c0-f713-473b-b75a-30e7eda27791"
  header_title = "PrinzPiuz"
  header_subtitle = "Software Engineer | Ziff Davis | Cochin" # Your header subtitle
  home_image = "/images/avatar.jpeg"
  recent_posts = 5
  mainSections = ["posts", "post", "blog"]
  [[params.social]]
    fa_icon = "fab fa-github fa-1x"
    href = "https://github.com/prinzpiuz"
  [[params.social]]
    fa_icon = "fab fa-twitter fa-1x"
    href = "https://twitter.com/prinzpiuz/"
  [[params.social]]
    fa_icon = "fab fa-mastodon"
    href = "https://elk.zone/aana.site/@prinzpiuz"
  [[params.social]]
    fa_icon = "fas fa-images"
    href = "https://portfolio.pixelfed.social/prinzpiuz"
  [[params.social]]
    fa_icon = "fas fa-film"
    href = "/reviews/"
    name = "reviews"
